apiVersion: v1
kind: Service
metadata:
  name: demo-app1-clusterip-service
  labels:
    app: demo-app1
spec:
  type: ClusterIP
  selector:
    app: demo-app1
  ports:
    - port: 80
      targetPort: 80
