apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app2-deployment
  labels:
    app: demo-app2 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app2
  template:
    metadata:
      labels:
        app: demo-app2
    spec:
      containers:
        - name: demo-app2
          image: nasserahmad/nginxdemo:latest
          ports:
            - containerPort: 80
