apiVersion: v1
kind: Service
metadata:
  name: demo-app2-clusterip-service
  labels:
    app: demo-app2
  annotations:
spec:
  type: ClusterIP
  selector:
    app: demo-app2
  ports:
    - port: 80
      targetPort: 80

   